### PR TITLE
Proposed updates:

### PR DESCRIPTION
**Pull request by lmzke**
Feel free to reject or adapt these proposed updates to your upstream pull request.  Squash my commit in with your latest updates when do you.  No credit desired, no need to leave my commit in the final log.

1. Correct off-by-one error in server response whitespace removal
2. Include banner response (before first command entered)

- [x] I have read the contributing guide lines at https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation contribution agreement at https://suricata-ids.org/about/contribution-agreement/

### CODE REVIEW

**Comment by lmzke** [comment]
The off-by-one ends up stripping the final non-whitespace character from the response line.  Many servers end responses with a period so it is not as noticeable when that is cut, versus the last letter of a word.

**Comment by jlucovsky** [comment]
> The off-by-one ends up stripping the final non-whitespace character from the response line. Many servers end responses with a period so it is not as noticeable when that is cut, versus the last letter of a word.

Good catch. Thanks.

**Comment by jlucovsky** [comment]
Thanks for your contributions!  I will incorporate in an updated PR.

**Comment by jlucovsky** [comment]
Changes included in https://github.com/OISF/suricata/pull/3887

**Pull request closed without merging**
